//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePredict
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceDataEntities
    {
        public int Id { get; set; }
        public int MeetingID { get; set; }
        public System.DateTime Date { get; set; }
        public int JetBet { get; set; }
        public string Track { get; set; }
        public string DayType { get; set; }
        public string MeetingType { get; set; }
        public string Club { get; set; }
        public string MeetingName { get; set; }
        public string TrackCondition { get; set; }
        public int TrackConditionScale { get; set; }
        public string TrackWeather { get; set; }
        public string Rail { get; set; }
        public int RaceID { get; set; }
        public int RaceNumber { get; set; }
        public string RaceGroup { get; set; }
        public string RaceType { get; set; }
        public int Distance { get; set; }
        public string RaceClass { get; set; }
        public string RaceName { get; set; }
        public decimal Stake1 { get; set; }
        public System.DateTime Time { get; set; }
        public string NoAllowances { get; set; }
        public string MinWeight { get; set; }
        public string ClassAge { get; set; }
        public string Class { get; set; }
        public string ClassGender { get; set; }
        public string ClassWeight { get; set; }
        public string RaceTrackCondition { get; set; }
        public int RaceTrackConditionScale { get; set; }
        public string RaceWeather { get; set; }
        public int HorseID { get; set; }
        public int ToteNumber { get; set; }
        public int Barrier { get; set; }
        public string HorseName { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public decimal Weight { get; set; }
        public string Finishingposition { get; set; }
        public string Actualtime { get; set; }
        public string Last600mTime { get; set; }
        public decimal Decimalmargin { get; set; }
        public string Traditionalmargin { get; set; }
        public string Trainer { get; set; }
        public string TrainerLocation { get; set; }
        public string StartingPriceWin { get; set; }
        public string StartingPricePlace { get; set; }
        public decimal Stake2 { get; set; }
        public string JockeyName { get; set; }
        public decimal CarriedWeight { get; set; }
        public decimal WeightDifference { get; set; }
        public int DomesticRating { get; set; }
        public int HurdlesRating { get; set; }
        public int SteeplesRating { get; set; }
        public string GearWorn { get; set; }
        public int SireID { get; set; }
        public string Sire { get; set; }
        public int DamID { get; set; }
        public string Dam { get; set; }
    }
}
